// ═══════════════════════════════════════════════════════════════════
// PFLX Battle Arena — Mock Data
// Mirrors X-Coin mock players + arena-specific stats
// ═══════════════════════════════════════════════════════════════════

import {
  ArenaPlayer,
  Battle,
  QuizQuestion,
  LeaderboardEntry,
} from "./types";

// ── Mock Players (synced from X-Coin app) ─────────────────────────

export const mockArenaPlayers: ArenaPlayer[] = [
  {
    id: "player-1",
    name: "Marcus Johnson",
    brandName: "MJ Studios",
    role: "player",
    avatar: "👨‍🎨",
    digitalBadges: 12,
    xcoin: 8500,
    totalXcoin: 25000,
    level: 4,
    rank: 3,
    cohort: "Alpha Cohort",
    pathway: "Content Creator",
    badgeCounts: { signature: 2, executive: 3, premium: 3, primary: 4 },
    arenaStats: {
      totalBattles: 28,
      wins: 18,
      losses: 8,
      draws: 2,
      winStreak: 4,
      bestWinStreak: 7,
      totalXCWagered: 14000,
      totalXCWon: 9200,
      totalXCLost: 4800,
      arenaRank: "Gold",
      arenaPoints: 2100,
      favoriteMode: "quiz_duel",
    },
  },
  {
    id: "player-2",
    name: "Aaliyah Carter",
    brandName: "Nova Designs",
    role: "player",
    avatar: "👩‍💻",
    digitalBadges: 18,
    xcoin: 15200,
    totalXcoin: 42000,
    level: 5,
    rank: 4,
    cohort: "Alpha Cohort",
    pathway: "Digital Artist",
    badgeCounts: { signature: 4, executive: 5, premium: 4, primary: 5 },
    arenaStats: {
      totalBattles: 45,
      wins: 32,
      losses: 10,
      draws: 3,
      winStreak: 8,
      bestWinStreak: 12,
      totalXCWagered: 22500,
      totalXCWon: 18400,
      totalXCLost: 4100,
      arenaRank: "Platinum",
      arenaPoints: 3800,
      favoriteMode: "project_showdown",
    },
  },
  {
    id: "player-3",
    name: "DeShawn Williams",
    brandName: "Pixel Empire",
    role: "player",
    avatar: "🎮",
    digitalBadges: 9,
    xcoin: 5300,
    totalXcoin: 18000,
    level: 3,
    rank: 2,
    cohort: "Beta Cohort",
    pathway: "Game Designer",
    badgeCounts: { signature: 1, executive: 2, premium: 3, primary: 3 },
    arenaStats: {
      totalBattles: 15,
      wins: 9,
      losses: 5,
      draws: 1,
      winStreak: 2,
      bestWinStreak: 5,
      totalXCWagered: 7500,
      totalXCWon: 4800,
      totalXCLost: 2700,
      arenaRank: "Silver",
      arenaPoints: 980,
      favoriteMode: "strategy_battle",
    },
  },
  {
    id: "player-4",
    name: "Jasmine Lee",
    brandName: "SoundWave J",
    role: "player",
    avatar: "🎵",
    digitalBadges: 14,
    xcoin: 11800,
    totalXcoin: 35000,
    level: 4,
    rank: 3,
    cohort: "Alpha Cohort",
    pathway: "Sound Designer",
    badgeCounts: { signature: 3, executive: 4, premium: 3, primary: 4 },
    arenaStats: {
      totalBattles: 35,
      wins: 22,
      losses: 11,
      draws: 2,
      winStreak: 3,
      bestWinStreak: 9,
      totalXCWagered: 17500,
      totalXCWon: 12600,
      totalXCLost: 4900,
      arenaRank: "Gold",
      arenaPoints: 2450,
      favoriteMode: "quiz_duel",
    },
  },
  {
    id: "player-5",
    name: "Tyler Brooks",
    brandName: "CodeForge",
    role: "player",
    avatar: "💻",
    digitalBadges: 22,
    xcoin: 28000,
    totalXcoin: 68000,
    level: 6,
    rank: 5,
    cohort: "Beta Cohort",
    pathway: "CS/AI Specialist",
    badgeCounts: { signature: 5, executive: 6, premium: 5, primary: 6 },
    arenaStats: {
      totalBattles: 62,
      wins: 48,
      losses: 12,
      draws: 2,
      winStreak: 11,
      bestWinStreak: 15,
      totalXCWagered: 31000,
      totalXCWon: 28800,
      totalXCLost: 2200,
      arenaRank: "Diamond",
      arenaPoints: 6200,
      favoriteMode: "quiz_duel",
    },
  },
  {
    id: "player-6",
    name: "Maya Robinson",
    brandName: "3D Maya",
    role: "player",
    avatar: "🎯",
    digitalBadges: 7,
    xcoin: 3200,
    totalXcoin: 12000,
    level: 2,
    rank: 2,
    cohort: "Beta Cohort",
    pathway: "3D Modeler",
    badgeCounts: { signature: 1, executive: 1, premium: 2, primary: 3 },
    arenaStats: {
      totalBattles: 10,
      wins: 4,
      losses: 5,
      draws: 1,
      winStreak: 1,
      bestWinStreak: 3,
      totalXCWagered: 5000,
      totalXCWon: 2400,
      totalXCLost: 2600,
      arenaRank: "Bronze",
      arenaPoints: 320,
      favoriteMode: "team_clash",
    },
  },
  {
    id: "player-7",
    name: "Kai Nakamura",
    brandName: "Kai Ventures",
    role: "player",
    avatar: "🚀",
    digitalBadges: 16,
    xcoin: 19500,
    totalXcoin: 52000,
    level: 5,
    rank: 4,
    cohort: "Alpha Cohort",
    pathway: "Professional Entrepreneur",
    badgeCounts: { signature: 4, executive: 4, premium: 4, primary: 4 },
    arenaStats: {
      totalBattles: 40,
      wins: 28,
      losses: 10,
      draws: 2,
      winStreak: 6,
      bestWinStreak: 10,
      totalXCWagered: 20000,
      totalXCWon: 16800,
      totalXCLost: 3200,
      arenaRank: "Platinum",
      arenaPoints: 3500,
      favoriteMode: "strategy_battle",
    },
  },
  {
    id: "player-8",
    name: "Zara Mitchell",
    brandName: "Zara Creates",
    role: "player",
    avatar: "✨",
    digitalBadges: 20,
    xcoin: 22000,
    totalXcoin: 58000,
    level: 5,
    rank: 5,
    cohort: "Alpha Cohort",
    pathway: "Content Creator",
    badgeCounts: { signature: 5, executive: 5, premium: 5, primary: 5 },
    arenaStats: {
      totalBattles: 55,
      wins: 40,
      losses: 13,
      draws: 2,
      winStreak: 9,
      bestWinStreak: 14,
      totalXCWagered: 27500,
      totalXCWon: 24000,
      totalXCLost: 3500,
      arenaRank: "Diamond",
      arenaPoints: 5800,
      favoriteMode: "project_showdown",
    },
  },
];

// ── Mock Quiz Questions ───────────────────────────────────────────

export const mockQuizQuestions: QuizQuestion[] = [
  {
    id: "q-1",
    question: "What does 'XC' stand for in the PFLX ecosystem?",
    options: ["X-Credit", "X-Coin", "X-Currency", "X-Cash"],
    correctAnswer: 1,
    category: "pflx_lore",
    difficulty: "easy",
    timeLimit: 15,
  },
  {
    id: "q-2",
    question: "In entrepreneurship, what is a 'pitch deck'?",
    options: [
      "A deck of playing cards for team building",
      "A presentation to attract investors",
      "A collection of product samples",
      "A legal document for startups",
    ],
    correctAnswer: 1,
    category: "entrepreneurship",
    difficulty: "easy",
    timeLimit: 15,
  },
  {
    id: "q-3",
    question: "Which color model is used for digital screens?",
    options: ["CMYK", "RGB", "Pantone", "HSL"],
    correctAnswer: 1,
    category: "digital_art",
    difficulty: "easy",
    timeLimit: 15,
  },
  {
    id: "q-4",
    question: "What is the frame rate typically used in film production?",
    options: ["30 fps", "24 fps", "60 fps", "120 fps"],
    correctAnswer: 1,
    category: "content_creation",
    difficulty: "medium",
    timeLimit: 20,
  },
  {
    id: "q-5",
    question: "In 3D modeling, what is a 'mesh'?",
    options: [
      "A texture applied to a surface",
      "A collection of vertices, edges, and faces",
      "A type of lighting effect",
      "A rendering technique",
    ],
    correctAnswer: 1,
    category: "3d_modeling",
    difficulty: "medium",
    timeLimit: 20,
  },
  {
    id: "q-6",
    question: "What does 'AI' stand for?",
    options: [
      "Automated Intelligence",
      "Artificial Intelligence",
      "Advanced Integration",
      "Algorithmic Innovation",
    ],
    correctAnswer: 1,
    category: "cs_ai",
    difficulty: "easy",
    timeLimit: 10,
  },
  {
    id: "q-7",
    question: "Which DAW is known for its step sequencer and is popular in hip-hop production?",
    options: ["Ableton Live", "FL Studio", "Logic Pro", "Pro Tools"],
    correctAnswer: 1,
    category: "sound_design",
    difficulty: "medium",
    timeLimit: 20,
  },
  {
    id: "q-8",
    question: "What game engine uses a visual scripting system called 'Blueprints'?",
    options: ["Unity", "Godot", "Unreal Engine", "GameMaker"],
    correctAnswer: 2,
    category: "game_design",
    difficulty: "medium",
    timeLimit: 20,
  },
  {
    id: "q-9",
    question: "In the PFLX rank system, what is the highest Evolution Rank?",
    options: ["Chief", "Senior", "Partner", "Director"],
    correctAnswer: 2,
    category: "pflx_lore",
    difficulty: "medium",
    timeLimit: 15,
  },
  {
    id: "q-10",
    question: "What is the purpose of a 'wireframe' in UX design?",
    options: [
      "To add color and branding",
      "To create a basic structural layout",
      "To write the final copy",
      "To test server performance",
    ],
    correctAnswer: 1,
    category: "digital_art",
    difficulty: "easy",
    timeLimit: 15,
  },
  {
    id: "q-11",
    question: "What programming concept allows code to be reused by creating a template for objects?",
    options: ["Variable", "Loop", "Class", "Array"],
    correctAnswer: 2,
    category: "cs_ai",
    difficulty: "medium",
    timeLimit: 20,
  },
  {
    id: "q-12",
    question: "Which badge type carries the highest weight in PFLX status scoring?",
    options: ["Primary", "Premium", "Executive", "Signature"],
    correctAnswer: 3,
    category: "pflx_lore",
    difficulty: "hard",
    timeLimit: 15,
  },
];

// ── Mock Active Battles ───────────────────────────────────────────

export const mockActiveBattles: Battle[] = [
  {
    id: "battle-1",
    mode: "quiz_duel",
    status: "waiting",
    createdBy: "player-1",
    createdAt: new Date().toISOString(),
    players: [
      {
        playerId: "player-1",
        player: mockArenaPlayers[0],
        score: 0,
        isReady: true,
        joinedAt: new Date().toISOString(),
      },
    ],
    wagerAmount: 500,
    prizePool: 500,
    rounds: [],
    currentRound: 0,
    totalRounds: 5,
    settings: {
      timePerQuestion: 15,
      difficulty: "mixed",
      allowSpectators: true,
      isRanked: true,
    },
  },
  {
    id: "battle-2",
    mode: "team_clash",
    status: "waiting",
    createdBy: "player-5",
    createdAt: new Date().toISOString(),
    players: [
      {
        playerId: "player-5",
        player: mockArenaPlayers[4],
        teamId: "team-a",
        score: 0,
        isReady: true,
        joinedAt: new Date().toISOString(),
      },
      {
        playerId: "player-7",
        player: mockArenaPlayers[6],
        teamId: "team-a",
        score: 0,
        isReady: true,
        joinedAt: new Date().toISOString(),
      },
    ],
    teams: [
      { id: "team-a", name: "Code Crushers", playerIds: ["player-5", "player-7"], score: 0, color: "#00e5ff" },
      { id: "team-b", name: "Design Dragons", playerIds: [], score: 0, color: "#e040fb" },
    ],
    wagerAmount: 1000,
    prizePool: 2000,
    rounds: [],
    currentRound: 0,
    totalRounds: 3,
    settings: {
      timePerQuestion: 30,
      difficulty: "medium",
      allowSpectators: true,
      isRanked: true,
    },
  },
];

// ── Mock Leaderboard ──────────────────────────────────────────────

export const mockLeaderboard: LeaderboardEntry[] = mockArenaPlayers
  .sort((a, b) => b.arenaStats.arenaPoints - a.arenaStats.arenaPoints)
  .map((player, index) => ({
    playerId: player.id,
    player,
    position: index + 1,
    arenaPoints: player.arenaStats.arenaPoints,
    wins: player.arenaStats.wins,
    losses: player.arenaStats.losses,
    winRate: Math.round((player.arenaStats.wins / Math.max(player.arenaStats.totalBattles, 1)) * 100),
    totalXCWon: player.arenaStats.totalXCWon,
    streak: player.arenaStats.winStreak,
  }));
